apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-webhook
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alert-webhook
    spec:
      containers:
      - name: alert-webhook
        image: registry.cn-beijing.aliyuncs.com/cloudt-pub/alert-webhook:v1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 1000M
          requests:
            cpu: 1
            memory: 1000M
        volumeMounts:
        - mountPath: /usr/app/conf/email.yaml
          name: alert
          readOnly: true
          subPath: email.yaml
      imagePullSecrets:
      - name: ali-img-secret
      dnsPolicy: ClusterFirst
      hostname: alert-webhook
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - configMap:
          defaultMode: 420
          name: alert-config
        name: alert